name: API Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
 
      - name: Install sccache
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then
            SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz"
          elif [ "$ARCH" = "aarch64" ]; then
            SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-aarch64-unknown-linux-musl.tar.gz"
          elif [ "$ARCH" = "armv7l" ]; then
            SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-armv7-unknown-linux-musleabi.tar.gz"
          elif [ "$ARCH" = "i686" ]; then
            SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-i686-unknown-linux-musl.tar.gz"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          curl -L "$SCCACHE_URL" | tar xz
          sudo mv sccache-*/sccache /usr/local/bin/
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug/incremental
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Perform fast syntax check
        run: cargo check

      - name: Build project
        run: cargo build --debug

      - name: Start server
        run: ./target/debug/osphor &

      - name: Wait for server to start
        run: sleep 3s

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run API tests
        run: cargo nextest run --test api

      - name: Print server logs on failure
        if: failure()
        run: cat server.log

      - name: Stop server
        run: pkill osphor || true
