name: API Tests

on:
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Build Project
        run: cargo build --release

      - name: Start Game Server
        run: ./target/release/osphor &
      
      - name: Wait for Server to Start
        run: sleep 3

      - name: Run API Tests
        run: cargo test --test api_tests -- --test-threads=1

      - name: Stop Game Server
        run: pkill osphor || true
